services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ../Backend_PD
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8180:8180"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:
    build:
      context: ../Frontend_PD
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - backend

volumes:
  mysql_data:
